ADJECTIVES = '''
    wrathful      worthy         weird             warm             volatile     veiled      vacuous       useless
    upset         unsoiled       unsightly         unpronounceable  unfriendly   unfree      unfit         unfaithful
    unchaste      unbroken       unbound           unblessed        unbefitting  unaltered   unabused      unable
    ugly          tongued        thorny            thirsty          thick        terminal    ten-sided     teeming
    tangerine     taken          substantial       stupefying       stringy      strange     stillborn     sticky
    stagnant      spongy         sour              soul-destroying  smoldering   smitten     slain         six-sided
    shifting      shadowy        severed           seven-sided      serene       salty       rust-red      royal
    rotten        riddled        resentful         regrettable      reeking      rare        rank          rancid
    quiescent     putrid         putrid            putrescent       prehistoric  predatory   predaceous    porous
    poisonous     pierced        phlegmatic        petrifying       pessimal     pathetic    odorless      oddish
    obsessed      obscene        numb              nine-sided       nasty        mysterious  mute          musky
    morose        moribund       moldy             miasmic          material     many-lobed  malodorous    malign
    maimed        luminescent    low-cut           lousy            live         limp        lifeless      leering
    leaky         layered        latent            lackluster       jagged       irregular   iridescent    intangible
    infinite      inept          incomprehensible  in-between       improper     idle        hunted        hideous
    heavy         hairy          guilty            grotesque        grey         greedy      gory          gorgeous
    gooey         golden-brown   golden            ghastly          frostbitten  fresh-cut   freakish      frantic
    fossilized    formless       formidable        floccose         five-lobed   firstborn   filthy        fickle
    fetid         fertile        fearful           fatal            familiar     fallen      fallacious    faint
    faceless      extinct        esoteric          errant           emergent     elastic     eight-sided   eerie
    ebon          dysphoric      dying             dumb             dull-purple  dull        dull          dull
    dormant       doomed         disfigured        dirty            defenseless  deep-pink   deep          deconsecrated
    deathlike     deadly         dead              dark-blue        dark         curly       curious       cured
    cunning       crystalline    cryptic           crying           crumbly      crimson     crested       creepy
    crazy         corrupt        corporeal         contemptible     contained    concrete    cloudy        chopped
    chained       caustic        catholic          cathartic        captive      cancerous   cabalistic    burnt
    buoyant       bronze-red     bronze            broken           bright-red   breathless  bound         bound
    bottomless    bony           bodiless          blue-lilac       blue         bloody      bloodthirsty  bloodsucking
    bloodstained  bloodcurdling  blonde            blistered        blank        bitter      bilgy         bewitched
    befouled      beardless      bastardly         barbed           baleful      balding     awkward       awful
    atrocious     arcane         appalling         antic            anonymous    angry       ample         ambiguous
    amber-green   amber          aghast            activated        acidic       abused      abstruse      abject
    '''.split()
