NOUNS = '''
    yolk         writing        wrath      wound          worm              wings         whistle       watchdog
    waste        vomit          vermin     variation      underachievement  tusk          troll         trick
    transplant   transgression  tooth      tongue         tickle            tick          thorn         thistle
    thing        terror         tentacle   tease          surrender         surge         sucker        substance
    storm        stone          stew       stalk          squid             sprout        sponge        spill
    spider       sphere         spectacle  speck          spawn             soul          solution      snout
    snake        smell          sloth      slime          slice             sleeper       slave         sinew
    shell        shape          seizure    seed           schism            scam          scale         sainthood
    root         robe           roach      rinse          remains           relay         rejuvenation  realization
    reaction     ransom         pupa       pride          prey              predator      potion        pornography
    polyp        plum           pleasure   pitch          pigeon            phenomenon    pest          periwinkle
    percolation  parasite       pair       oyster         orphan            orgasm        organism      orchid
    object       nail           mushroom   murder         mucus             movement      mother        mold
    mist         mildew         metal      mesh           meddling          mayhem        masterpiece   masonry
    mask         manhood        maggot     lust           loop              living_thing  liquor        liquid
    lining       laceration     knife      kitten         kiss              jumper        jest          instrument
    injustice    injury         influence  indulgence     incursion         impulse       imago         hound
    horn         hook           hoof       heirloom       heart             hawk          hare          hair
    gulp         guardian       grass      goat           gnat              gluttony      glowworm      gasp
    game         fusion         fungus     frustration    frog              foul          foot          food
    fog          foal           fluke      fluff          flower            flicker       flea          flattery
    flask        flare          firefly    finger         filtration        female        feeder        feather
    fart         fang           failure    face           fabrication       extract       exodus        evil
    envy         enema          embryo     egress         echo              eater         ear           dwarf
    dust         drop           draft      domestication  distortion        dew           depravity     deity
    death        daughter       dash       dagger         culture           crutch        crow          critter
    creeper      creation       crab       corruption     cocoon            claw          chip          child
    cell         catch          carving    carrot         carnival          cancer        butterfly     burn
    buildup      brush          brew       bottle         boot              book          bone          blunder
    blot         blood          blink      bite           bird              benthos       beak          basket
    bark         ball           baby       axolotl        ashes             artifact      arson         armor
    apparition   antenna        alms       alienation     advent            adornment     abomination   abandonment
    '''.split()
