
#include "words.h"

const char * const adjectives[256] = {
    "wrathful",             /* 0   */
    "worthy",               /* 1   */
    "weird",                /* 2   */
    "warm",                 /* 3   */
    "volatile",             /* 4   */
    "veiled",               /* 5   */
    "vacuous",              /* 6   */
    "useless",              /* 7   */
    "upset",                /* 8   */
    "unsoiled",             /* 9   */
    "unsightly",            /* 10  */
    "unpronounceable",      /* 11  */
    "unfriendly",           /* 12  */
    "unfree",               /* 13  */
    "unfit",                /* 14  */
    "unfaithful",           /* 15  */
    "unchaste",             /* 16  */
    "unbroken",             /* 17  */
    "unbound",              /* 18  */
    "unblessed",            /* 19  */
    "unbefitting",          /* 20  */
    "unaltered",            /* 21  */
    "unabused",             /* 22  */
    "unable",               /* 23  */
    "ugly",                 /* 24  */
    "tongued",              /* 25  */
    "thorny",               /* 26  */
    "thirsty",              /* 27  */
    "thick",                /* 28  */
    "terminal",             /* 29  */
    "ten-sided",            /* 30  */
    "teeming",              /* 31  */
    "tangerine",            /* 32  */
    "taken",                /* 33  */
    "substantial",          /* 34  */
    "stupefying",           /* 35  */
    "stringy",              /* 36  */
    "strange",              /* 37  */
    "stillborn",            /* 38  */
    "sticky",               /* 39  */
    "stagnant",             /* 40  */
    "spongy",               /* 41  */
    "sour",                 /* 42  */
    "soul-destroying",      /* 43  */
    "smoldering",           /* 44  */
    "smitten",              /* 45  */
    "slain",                /* 46  */
    "six-sided",            /* 47  */
    "shifting",             /* 48  */
    "shadowy",              /* 49  */
    "severed",              /* 50  */
    "seven-sided",          /* 51  */
    "serene",               /* 52  */
    "salty",                /* 53  */
    "rust-red",             /* 54  */
    "royal",                /* 55  */
    "rotten",               /* 56  */
    "riddled",              /* 57  */
    "resentful",            /* 58  */
    "regrettable",          /* 59  */
    "reeking",              /* 60  */
    "rare",                 /* 61  */
    "rank",                 /* 62  */
    "rancid",               /* 63  */
    "quiescent",            /* 64  */
    "putrid",               /* 65  */
    "putrid",               /* 66  */
    "putrescent",           /* 67  */
    "prehistoric",          /* 68  */
    "predatory",            /* 69  */
    "predaceous",           /* 70  */
    "porous",               /* 71  */
    "poisonous",            /* 72  */
    "pierced",              /* 73  */
    "phlegmatic",           /* 74  */
    "petrifying",           /* 75  */
    "pessimal",             /* 76  */
    "pathetic",             /* 77  */
    "odorless",             /* 78  */
    "oddish",               /* 79  */
    "obsessed",             /* 80  */
    "obscene",              /* 81  */
    "numb",                 /* 82  */
    "nine-sided",           /* 83  */
    "nasty",                /* 84  */
    "mysterious",           /* 85  */
    "mute",                 /* 86  */
    "musky",                /* 87  */
    "morose",               /* 88  */
    "moribund",             /* 89  */
    "moldy",                /* 90  */
    "miasmic",              /* 91  */
    "material",             /* 92  */
    "many-lobed",           /* 93  */
    "malodorous",           /* 94  */
    "malign",               /* 95  */
    "maimed",               /* 96  */
    "luminescent",          /* 97  */
    "low-cut",              /* 98  */
    "lousy",                /* 99  */
    "live",                 /* 100 */
    "limp",                 /* 101 */
    "lifeless",             /* 102 */
    "leering",              /* 103 */
    "leaky",                /* 104 */
    "layered",              /* 105 */
    "latent",               /* 106 */
    "lackluster",           /* 107 */
    "jagged",               /* 108 */
    "irregular",            /* 109 */
    "iridescent",           /* 110 */
    "intangible",           /* 111 */
    "infinite",             /* 112 */
    "inept",                /* 113 */
    "incomprehensible",     /* 114 */
    "in-between",           /* 115 */
    "improper",             /* 116 */
    "idle",                 /* 117 */
    "hunted",               /* 118 */
    "hideous",              /* 119 */
    "heavy",                /* 120 */
    "hairy",                /* 121 */
    "guilty",               /* 122 */
    "grotesque",            /* 123 */
    "grey",                 /* 124 */
    "greedy",               /* 125 */
    "gory",                 /* 126 */
    "gorgeous",             /* 127 */
    "gooey",                /* 128 */
    "golden-brown",         /* 129 */
    "golden",               /* 130 */
    "ghastly",              /* 131 */
    "frostbitten",          /* 132 */
    "fresh-cut",            /* 133 */
    "freakish",             /* 134 */
    "frantic",              /* 135 */
    "fossilized",           /* 136 */
    "formless",             /* 137 */
    "formidable",           /* 138 */
    "floccose",             /* 139 */
    "five-lobed",           /* 140 */
    "firstborn",            /* 141 */
    "filthy",               /* 142 */
    "fickle",               /* 143 */
    "fetid",                /* 144 */
    "fertile",              /* 145 */
    "fearful",              /* 146 */
    "fatal",                /* 147 */
    "familiar",             /* 148 */
    "fallen",               /* 149 */
    "fallacious",           /* 150 */
    "faint",                /* 151 */
    "faceless",             /* 152 */
    "extinct",              /* 153 */
    "esoteric",             /* 154 */
    "errant",               /* 155 */
    "emergent",             /* 156 */
    "elastic",              /* 157 */
    "eight-sided",          /* 158 */
    "eerie",                /* 159 */
    "ebon",                 /* 160 */
    "dysphoric",            /* 161 */
    "dying",                /* 162 */
    "dumb",                 /* 163 */
    "dull-purple",          /* 164 */
    "dull",                 /* 165 */
    "dull",                 /* 166 */
    "dull",                 /* 167 */
    "dormant",              /* 168 */
    "doomed",               /* 169 */
    "disfigured",           /* 170 */
    "dirty",                /* 171 */
    "defenseless",          /* 172 */
    "deep-pink",            /* 173 */
    "deep",                 /* 174 */
    "deconsecrated",        /* 175 */
    "deathlike",            /* 176 */
    "deadly",               /* 177 */
    "dead",                 /* 178 */
    "dark-blue",            /* 179 */
    "dark",                 /* 180 */
    "curly",                /* 181 */
    "curious",              /* 182 */
    "cured",                /* 183 */
    "cunning",              /* 184 */
    "crystalline",          /* 185 */
    "cryptic",              /* 186 */
    "crying",               /* 187 */
    "crumbly",              /* 188 */
    "crimson",              /* 189 */
    "crested",              /* 190 */
    "creepy",               /* 191 */
    "crazy",                /* 192 */
    "corrupt",              /* 193 */
    "corporeal",            /* 194 */
    "contemptible",         /* 195 */
    "contained",            /* 196 */
    "concrete",             /* 197 */
    "cloudy",               /* 198 */
    "chopped",              /* 199 */
    "chained",              /* 200 */
    "caustic",              /* 201 */
    "catholic",             /* 202 */
    "cathartic",            /* 203 */
    "captive",              /* 204 */
    "cancerous",            /* 205 */
    "cabalistic",           /* 206 */
    "burnt",                /* 207 */
    "buoyant",              /* 208 */
    "bronze-red",           /* 209 */
    "bronze",               /* 210 */
    "broken",               /* 211 */
    "bright-red",           /* 212 */
    "breathless",           /* 213 */
    "bound",                /* 214 */
    "bound",                /* 215 */
    "bottomless",           /* 216 */
    "bony",                 /* 217 */
    "bodiless",             /* 218 */
    "blue-lilac",           /* 219 */
    "blue",                 /* 220 */
    "bloody",               /* 221 */
    "bloodthirsty",         /* 222 */
    "bloodsucking",         /* 223 */
    "bloodstained",         /* 224 */
    "bloodcurdling",        /* 225 */
    "blonde",               /* 226 */
    "blistered",            /* 227 */
    "blank",                /* 228 */
    "bitter",               /* 229 */
    "bilgy",                /* 230 */
    "bewitched",            /* 231 */
    "befouled",             /* 232 */
    "beardless",            /* 233 */
    "bastardly",            /* 234 */
    "barbed",               /* 235 */
    "baleful",              /* 236 */
    "balding",              /* 237 */
    "awkward",              /* 238 */
    "awful",                /* 239 */
    "atrocious",            /* 240 */
    "arcane",               /* 241 */
    "appalling",            /* 242 */
    "antic",                /* 243 */
    "anonymous",            /* 244 */
    "angry",                /* 245 */
    "ample",                /* 246 */
    "ambiguous",            /* 247 */
    "amber-green",          /* 248 */
    "amber",                /* 249 */
    "aghast",               /* 250 */
    "activated",            /* 251 */
    "acidic",               /* 252 */
    "abused",               /* 253 */
    "abstruse",             /* 254 */
    "abject",               /* 255 */
};

