
#include "words.h"

const char * const adjectives[256] = {
    "aardvark",  /* 0   */
    "absurd",    /* 1   */
    "accrue",    /* 2   */
    "acme",      /* 3   */
    "adrift",    /* 4   */
    "adult",     /* 5   */
    "afflict",   /* 6   */
    "ahead",     /* 7   */
    "aimless",   /* 8   */
    "Algol",     /* 9   */
    "allow",     /* 10  */
    "alone",     /* 11  */
    "ammo",      /* 12  */
    "ancient",   /* 13  */
    "apple",     /* 14  */
    "artist",    /* 15  */
    "assume",    /* 16  */
    "Athens",    /* 17  */
    "atlas",     /* 18  */
    "Aztec",     /* 19  */
    "baboon",    /* 20  */
    "backfield", /* 21  */
    "backward",  /* 22  */
    "banjo",     /* 23  */
    "beaming",   /* 24  */
    "bedlamp",   /* 25  */
    "beehive",   /* 26  */
    "beeswax",   /* 27  */
    "befriend",  /* 28  */
    "Belfast",   /* 29  */
    "berserk",   /* 30  */
    "billiard",  /* 31  */
    "bison",     /* 32  */
    "blackjack", /* 33  */
    "blockade",  /* 34  */
    "blowtorch", /* 35  */
    "bluebird",  /* 36  */
    "bombast",   /* 37  */
    "bookshelf", /* 38  */
    "brackish",  /* 39  */
    "breadline", /* 40  */
    "breakup",   /* 41  */
    "brickyard", /* 42  */
    "briefcase", /* 43  */
    "Burbank",   /* 44  */
    "button",    /* 45  */
    "buzzard",   /* 46  */
    "cement",    /* 47  */
    "chairlift", /* 48  */
    "chatter",   /* 49  */
    "checkup",   /* 50  */
    "chisel",    /* 51  */
    "choking",   /* 52  */
    "chopper",   /* 53  */
    "Christmas", /* 54  */
    "clamshell", /* 55  */
    "classic",   /* 56  */
    "classroom", /* 57  */
    "cleanup",   /* 58  */
    "clockwork", /* 59  */
    "cobra",     /* 60  */
    "commence",  /* 61  */
    "concert",   /* 62  */
    "cowbell",   /* 63  */
    "crackdown", /* 64  */
    "cranky",    /* 65  */
    "crowfoot",  /* 66  */
    "crucial",   /* 67  */
    "crumpled",  /* 68  */
    "crusade",   /* 69  */
    "cubic",     /* 70  */
    "dashboard", /* 71  */
    "deadbolt",  /* 72  */
    "deckhand",  /* 73  */
    "dogsled",   /* 74  */
    "dragnet",   /* 75  */
    "drainage",  /* 76  */
    "dreadful",  /* 77  */
    "drifter",   /* 78  */
    "dropper",   /* 79  */
    "drumbeat",  /* 80  */
    "drunken",   /* 81  */
    "Dupont",    /* 82  */
    "dwelling",  /* 83  */
    "eating",    /* 84  */
    "edict",     /* 85  */
    "egghead",   /* 86  */
    "eightball", /* 87  */
    "endorse",   /* 88  */
    "endow",     /* 89  */
    "enlist",    /* 90  */
    "erase",     /* 91  */
    "escape",    /* 92  */
    "exceed",    /* 93  */
    "eyeglass",  /* 94  */
    "eyetooth",  /* 95  */
    "facial",    /* 96  */
    "fallout",   /* 97  */
    "flagpole",  /* 98  */
    "flatfoot",  /* 99  */
    "flytrap",   /* 100 */
    "fracture",  /* 101 */
    "framework", /* 102 */
    "freedom",   /* 103 */
    "frighten",  /* 104 */
    "gazelle",   /* 105 */
    "Geiger",    /* 106 */
    "glitter",   /* 107 */
    "glucose",   /* 108 */
    "goggles",   /* 109 */
    "goldfish",  /* 110 */
    "gremlin",   /* 111 */
    "guidance",  /* 112 */
    "hamlet",    /* 113 */
    "highchair", /* 114 */
    "hockey",    /* 115 */
    "indoors",   /* 116 */
    "indulge",   /* 117 */
    "inverse",   /* 118 */
    "involve",   /* 119 */
    "island",    /* 120 */
    "jawbone",   /* 121 */
    "keyboard",  /* 122 */
    "kickoff",   /* 123 */
    "kiwi",      /* 124 */
    "klaxon",    /* 125 */
    "locale",    /* 126 */
    "lockup",    /* 127 */
    "merit",     /* 128 */
    "minnow",    /* 129 */
    "miser",     /* 130 */
    "Mohawk",    /* 131 */
    "mural",     /* 132 */
    "music",     /* 133 */
    "necklace",  /* 134 */
    "Neptune",   /* 135 */
    "newborn",   /* 136 */
    "nightbird", /* 137 */
    "Oakland",   /* 138 */
    "obtuse",    /* 139 */
    "offload",   /* 140 */
    "optic",     /* 141 */
    "orca",      /* 142 */
    "payday",    /* 143 */
    "peachy",    /* 144 */
    "pheasant",  /* 145 */
    "physique",  /* 146 */
    "playhouse", /* 147 */
    "Pluto",     /* 148 */
    "preclude",  /* 149 */
    "prefer",    /* 150 */
    "preshrunk", /* 151 */
    "printer",   /* 152 */
    "prowler",   /* 153 */
    "pupil",     /* 154 */
    "puppy",     /* 155 */
    "python",    /* 156 */
    "quadrant",  /* 157 */
    "quiver",    /* 158 */
    "quota",     /* 159 */
    "ragtime",   /* 160 */
    "ratchet",   /* 161 */
    "rebirth",   /* 162 */
    "reform",    /* 163 */
    "regain",    /* 164 */
    "reindeer",  /* 165 */
    "rematch",   /* 166 */
    "repay",     /* 167 */
    "retouch",   /* 168 */
    "revenge",   /* 169 */
    "reward",    /* 170 */
    "rhythm",    /* 171 */
    "ribcage",   /* 172 */
    "ringbolt",  /* 173 */
    "robust",    /* 174 */
    "rocker",    /* 175 */
    "ruffled",   /* 176 */
    "sailboat",  /* 177 */
    "sawdust",   /* 178 */
    "scallion",  /* 179 */
    "scenic",    /* 180 */
    "scorecard", /* 181 */
    "Scotland",  /* 182 */
    "seabird",   /* 183 */
    "select",    /* 184 */
    "sentence",  /* 185 */
    "shadow",    /* 186 */
    "shamrock",  /* 187 */
    "showgirl",  /* 188 */
    "skullcap",  /* 189 */
    "skydive",   /* 190 */
    "slingshot", /* 191 */
    "slowdown",  /* 192 */
    "snapline",  /* 193 */
    "snapshot",  /* 194 */
    "snowcap",   /* 195 */
    "snowslide", /* 196 */
    "solo",      /* 197 */
    "southward", /* 198 */
    "soybean",   /* 199 */
    "spaniel",   /* 200 */
    "spearhead", /* 201 */
    "spellbind", /* 202 */
    "spheroid",  /* 203 */
    "spigot",    /* 204 */
    "spindle",   /* 205 */
    "spyglass",  /* 206 */
    "stagehand", /* 207 */
    "stagnate",  /* 208 */
    "stairway",  /* 209 */
    "standard",  /* 210 */
    "stapler",   /* 211 */
    "steamship", /* 212 */
    "sterling",  /* 213 */
    "stockman",  /* 214 */
    "stopwatch", /* 215 */
    "stormy",    /* 216 */
    "sugar",     /* 217 */
    "surmount",  /* 218 */
    "suspense",  /* 219 */
    "sweatband", /* 220 */
    "swelter",   /* 221 */
    "tactics",   /* 222 */
    "talon",     /* 223 */
    "tapeworm",  /* 224 */
    "tempest",   /* 225 */
    "tiger",     /* 226 */
    "tissue",    /* 227 */
    "tonic",     /* 228 */
    "topmost",   /* 229 */
    "tracker",   /* 230 */
    "transit",   /* 231 */
    "trauma",    /* 232 */
    "treadmill", /* 233 */
    "Trojan",    /* 234 */
    "trouble",   /* 235 */
    "tumor",     /* 236 */
    "tunnel",    /* 237 */
    "tycoon",    /* 238 */
    "uncut",     /* 239 */
    "unearth",   /* 240 */
    "unwind",    /* 241 */
    "uproot",    /* 242 */
    "upset",     /* 243 */
    "upshot",    /* 244 */
    "vapor",     /* 245 */
    "village",   /* 246 */
    "virus",     /* 247 */
    "Vulcan",    /* 248 */
    "waffle",    /* 249 */
    "wallet",    /* 250 */
    "watchword", /* 251 */
    "wayside",   /* 252 */
    "willow",    /* 253 */
    "woodlark",  /* 254 */
    "Zulu"       /* 255 */
};

