
#include "words.h"

const char * const nouns[256] = {
    "adroitness",  /* 0   */
    "adviser",     /* 1   */
    "aftermath",   /* 2   */
    "aggregate",   /* 3   */
    "alkali",      /* 4   */
    "almighty",    /* 5   */
    "amulet",      /* 6   */
    "amusement",   /* 7   */
    "antenna",     /* 8   */
    "applicant",   /* 9   */
    "Apollo",      /* 10  */
    "armistice",   /* 11  */
    "article",     /* 12  */
    "asteroid",    /* 13  */
    "Atlantic",    /* 14  */
    "atmosphere",  /* 15  */
    "autopsy",     /* 16  */
    "Babylon",     /* 17  */
    "backwater",   /* 18  */
    "barbecue",    /* 19  */
    "belowground", /* 20  */
    "bifocals",    /* 21  */
    "bodyguard",   /* 22  */
    "bookseller",  /* 23  */
    "borderline",  /* 24  */
    "bottomless",  /* 25  */
    "Bradbury",    /* 26  */
    "bravado",     /* 27  */
    "Brazilian",   /* 28  */
    "breakaway",   /* 29  */
    "Burlington",  /* 30  */
    "businessman", /* 31  */
    "butterfat",   /* 32  */
    "Camelot",     /* 33  */
    "candidate",   /* 34  */
    "cannonball",  /* 35  */
    "Capricorn",   /* 36  */
    "caravan",     /* 37  */
    "caretaker",   /* 38  */
    "celebrate",   /* 39  */
    "cellulose",   /* 40  */
    "certify",     /* 41  */
    "chambermaid", /* 42  */
    "Cherokee",    /* 43  */
    "Chicago",     /* 44  */
    "clergyman",   /* 45  */
    "coherence",   /* 46  */
    "combustion",  /* 47  */
    "commando",    /* 48  */
    "company",     /* 49  */
    "component",   /* 50  */
    "concurrent",  /* 51  */
    "confidence",  /* 52  */
    "conformist",  /* 53  */
    "congregate",  /* 54  */
    "consensus",   /* 55  */
    "consulting",  /* 56  */
    "corporate",   /* 57  */
    "corrosion",   /* 58  */
    "councilman",  /* 59  */
    "crossover",   /* 60  */
    "crucifix",    /* 61  */
    "cumbersome",  /* 62  */
    "customer",    /* 63  */
    "Dakota",      /* 64  */
    "decadence",   /* 65  */
    "December",    /* 66  */
    "decimal",     /* 67  */
    "designing",   /* 68  */
    "detector",    /* 69  */
    "detergent",   /* 70  */
    "determine",   /* 71  */
    "dictator",    /* 72  */
    "dinosaur",    /* 73  */
    "direction",   /* 74  */
    "disable",     /* 75  */
    "disbelief",   /* 76  */
    "disruptive",  /* 77  */
    "distortion",  /* 78  */
    "document",    /* 79  */
    "embezzle",    /* 80  */
    "enchanting",  /* 81  */
    "enrollment",  /* 82  */
    "enterprise",  /* 83  */
    "equation",    /* 84  */
    "equipment",   /* 85  */
    "escapade",    /* 86  */
    "Eskimo",      /* 87  */
    "everyday",    /* 88  */
    "examine",     /* 89  */
    "existence",   /* 90  */
    "exodus",      /* 91  */
    "fascinate",   /* 92  */
    "filament",    /* 93  */
    "finicky",     /* 94  */
    "forever",     /* 95  */
    "fortitude",   /* 96  */
    "frequency",   /* 97  */
    "gadgetry",    /* 98  */
    "Galveston",   /* 99  */
    "getaway",     /* 100 */
    "glossary",    /* 101 */
    "gossamer",    /* 102 */
    "graduate",    /* 103 */
    "gravity",     /* 104 */
    "guitarist",   /* 105 */
    "hamburger",   /* 106 */
    "Hamilton",    /* 107 */
    "handiwork",   /* 108 */
    "hazardous",   /* 109 */
    "headwaters",  /* 110 */
    "hemisphere",  /* 111 */
    "hesitate",    /* 112 */
    "hideaway",    /* 113 */
    "holiness",    /* 114 */
    "hurricane",   /* 115 */
    "hydraulic",   /* 116 */
    "impartial",   /* 117 */
    "impetus",     /* 118 */
    "inception",   /* 119 */
    "indigo",      /* 120 */
    "inertia",     /* 121 */
    "infancy",     /* 122 */
    "inferno",     /* 123 */
    "informant",   /* 124 */
    "insincere",   /* 125 */
    "insurgent",   /* 126 */
    "integrate",   /* 127 */
    "intention",   /* 128 */
    "inventive",   /* 129 */
    "Istanbul",    /* 130 */
    "Jamaica",     /* 131 */
    "Jupiter",     /* 132 */
    "leprosy",     /* 133 */
    "letterhead",  /* 134 */
    "liberty",     /* 135 */
    "maritime",    /* 136 */
    "matchmaker",  /* 137 */
    "maverick",    /* 138 */
    "Medusa",      /* 139 */
    "megaton",     /* 140 */
    "microscope",  /* 141 */
    "microwave",   /* 142 */
    "midsummer",   /* 143 */
    "millionaire", /* 144 */
    "miracle",     /* 145 */
    "misnomer",    /* 146 */
    "molasses",    /* 147 */
    "molecule",    /* 148 */
    "Montana",     /* 149 */
    "monument",    /* 150 */
    "mosquito",    /* 151 */
    "narrative",   /* 152 */
    "nebula",      /* 153 */
    "newsletter",  /* 154 */
    "Norwegian",   /* 155 */
    "October",     /* 156 */
    "Ohio",        /* 157 */
    "onlooker",    /* 158 */
    "opulent",     /* 159 */
    "Orlando",     /* 160 */
    "outfielder",  /* 161 */
    "Pacific",     /* 162 */
    "pandemic",    /* 163 */
    "Pandora",     /* 164 */
    "paperweight", /* 165 */
    "paragon",     /* 166 */
    "paragraph",   /* 167 */
    "paramount",   /* 168 */
    "passenger",   /* 169 */
    "pedigree",    /* 170 */
    "Pegasus",     /* 171 */
    "penetrate",   /* 172 */
    "perceptive",  /* 173 */
    "performance", /* 174 */
    "pharmacy",    /* 175 */
    "phonetic",    /* 176 */
    "photograph",  /* 177 */
    "pioneer",     /* 178 */
    "pocketful",   /* 179 */
    "politeness",  /* 180 */
    "positive",    /* 181 */
    "potato",      /* 182 */
    "processor",   /* 183 */
    "provincial",  /* 184 */
    "proximate",   /* 185 */
    "puberty",     /* 186 */
    "publisher",   /* 187 */
    "pyramid",     /* 188 */
    "quantity",    /* 189 */
    "racketeer",   /* 190 */
    "rebellion",   /* 191 */
    "recipe",      /* 192 */
    "recover",     /* 193 */
    "repellent",   /* 194 */
    "replica",     /* 195 */
    "reproduce",   /* 196 */
    "resistor",    /* 197 */
    "responsive",  /* 198 */
    "retraction",  /* 199 */
    "retrieval",   /* 200 */
    "retrospect",  /* 201 */
    "revenue",     /* 202 */
    "revival",     /* 203 */
    "revolver",    /* 204 */
    "sandalwood",  /* 205 */
    "sardonic",    /* 206 */
    "Saturday",    /* 207 */
    "savagery",    /* 208 */
    "scavenger",   /* 209 */
    "sensation",   /* 210 */
    "sociable",    /* 211 */
    "souvenir",    /* 212 */
    "specialist",  /* 213 */
    "speculate",   /* 214 */
    "stethoscope", /* 215 */
    "stupendous",  /* 216 */
    "supportive",  /* 217 */
    "surrender",   /* 218 */
    "suspicious",  /* 219 */
    "sympathy",    /* 220 */
    "tambourine",  /* 221 */
    "telephone",   /* 222 */
    "therapist",   /* 223 */
    "tobacco",     /* 224 */
    "tolerance",   /* 225 */
    "tomorrow",    /* 226 */
    "torpedo",     /* 227 */
    "tradition",   /* 228 */
    "travesty",    /* 229 */
    "trombonist",  /* 230 */
    "truncated",   /* 231 */
    "typewriter",  /* 232 */
    "ultimate",    /* 233 */
    "undaunted",   /* 234 */
    "underfoot",   /* 235 */
    "unicorn",     /* 236 */
    "unify",       /* 237 */
    "universe",    /* 238 */
    "unravel",     /* 239 */
    "upcoming",    /* 240 */
    "vacancy",     /* 241 */
    "vagabond",    /* 242 */
    "vertigo",     /* 243 */
    "Virginia",    /* 244 */
    "visitor",     /* 245 */
    "vocalist",    /* 246 */
    "voyager",     /* 247 */
    "warranty",    /* 248 */
    "Waterloo",    /* 249 */
    "whimsical",   /* 250 */
    "Wichita",     /* 251 */
    "Wilmington",  /* 252 */
    "Wyoming",     /* 253 */
    "yesteryear",  /* 254 */
    "Yucatan",     /* 255 */
};

