
#include "words.h"

const char * const nouns[256] = {
    "yolk",             /* 0   */
    "writing",          /* 1   */
    "wrath",            /* 2   */
    "wound",            /* 3   */
    "worm",             /* 4   */
    "wings",            /* 5   */
    "whistle",          /* 6   */
    "watchdog",         /* 7   */
    "waste",            /* 8   */
    "vomit",            /* 9   */
    "vermin",           /* 10  */
    "variation",        /* 11  */
    "underachievement", /* 12  */
    "tusk",             /* 13  */
    "troll",            /* 14  */
    "trick",            /* 15  */
    "transplant",       /* 16  */
    "transgression",    /* 17  */
    "tooth",            /* 18  */
    "tongue",           /* 19  */
    "tickle",           /* 20  */
    "tick",             /* 21  */
    "thorn",            /* 22  */
    "thistle",          /* 23  */
    "thing",            /* 24  */
    "terror",           /* 25  */
    "tentacle",         /* 26  */
    "tease",            /* 27  */
    "surrender",        /* 28  */
    "surge",            /* 29  */
    "sucker",           /* 30  */
    "substance",        /* 31  */
    "storm",            /* 32  */
    "stone",            /* 33  */
    "stew",             /* 34  */
    "stalk",            /* 35  */
    "squid",            /* 36  */
    "sprout",           /* 37  */
    "sponge",           /* 38  */
    "spill",            /* 39  */
    "spider",           /* 40  */
    "sphere",           /* 41  */
    "spectacle",        /* 42  */
    "speck",            /* 43  */
    "spawn",            /* 44  */
    "soul",             /* 45  */
    "solution",         /* 46  */
    "snout",            /* 47  */
    "snake",            /* 48  */
    "smell",            /* 49  */
    "sloth",            /* 50  */
    "slime",            /* 51  */
    "slice",            /* 52  */
    "sleeper",          /* 53  */
    "slave",            /* 54  */
    "sinew",            /* 55  */
    "shell",            /* 56  */
    "shape",            /* 57  */
    "seizure",          /* 58  */
    "seed",             /* 59  */
    "schism",           /* 60  */
    "scam",             /* 61  */
    "scale",            /* 62  */
    "sainthood",        /* 63  */
    "root",             /* 64  */
    "robe",             /* 65  */
    "roach",            /* 66  */
    "rinse",            /* 67  */
    "remains",          /* 68  */
    "relay",            /* 69  */
    "rejuvenation",     /* 70  */
    "realization",      /* 71  */
    "reaction",         /* 72  */
    "ransom",           /* 73  */
    "pupa",             /* 74  */
    "pride",            /* 75  */
    "prey",             /* 76  */
    "predator",         /* 77  */
    "potion",           /* 78  */
    "pornography",      /* 79  */
    "polyp",            /* 80  */
    "plum",             /* 81  */
    "pleasure",         /* 82  */
    "pitch",            /* 83  */
    "pigeon",           /* 84  */
    "phenomenon",       /* 85  */
    "pest",             /* 86  */
    "periwinkle",       /* 87  */
    "percolation",      /* 88  */
    "parasite",         /* 89  */
    "pair",             /* 90  */
    "oyster",           /* 91  */
    "orphan",           /* 92  */
    "orgasm",           /* 93  */
    "organism",         /* 94  */
    "orchid",           /* 95  */
    "object",           /* 96  */
    "nail",             /* 97  */
    "mushroom",         /* 98  */
    "murder",           /* 99  */
    "mucus",            /* 100 */
    "movement",         /* 101 */
    "mother",           /* 102 */
    "mold",             /* 103 */
    "mist",             /* 104 */
    "mildew",           /* 105 */
    "metal",            /* 106 */
    "mesh",             /* 107 */
    "meddling",         /* 108 */
    "mayhem",           /* 109 */
    "masterpiece",      /* 110 */
    "masonry",          /* 111 */
    "mask",             /* 112 */
    "manhood",          /* 113 */
    "maggot",           /* 114 */
    "lust",             /* 115 */
    "loop",             /* 116 */
    "living_thing",     /* 117 */
    "liquor",           /* 118 */
    "liquid",           /* 119 */
    "lining",           /* 120 */
    "laceration",       /* 121 */
    "knife",            /* 122 */
    "kitten",           /* 123 */
    "kiss",             /* 124 */
    "jumper",           /* 125 */
    "jest",             /* 126 */
    "instrument",       /* 127 */
    "injustice",        /* 128 */
    "injury",           /* 129 */
    "influence",        /* 130 */
    "indulgence",       /* 131 */
    "incursion",        /* 132 */
    "impulse",          /* 133 */
    "imago",            /* 134 */
    "hound",            /* 135 */
    "horn",             /* 136 */
    "hook",             /* 137 */
    "hoof",             /* 138 */
    "heirloom",         /* 139 */
    "heart",            /* 140 */
    "hawk",             /* 141 */
    "hare",             /* 142 */
    "hair",             /* 143 */
    "gulp",             /* 144 */
    "guardian",         /* 145 */
    "grass",            /* 146 */
    "goat",             /* 147 */
    "gnat",             /* 148 */
    "gluttony",         /* 149 */
    "glowworm",         /* 150 */
    "gasp",             /* 151 */
    "game",             /* 152 */
    "fusion",           /* 153 */
    "fungus",           /* 154 */
    "frustration",      /* 155 */
    "frog",             /* 156 */
    "foul",             /* 157 */
    "foot",             /* 158 */
    "food",             /* 159 */
    "fog",              /* 160 */
    "foal",             /* 161 */
    "fluke",            /* 162 */
    "fluff",            /* 163 */
    "flower",           /* 164 */
    "flicker",          /* 165 */
    "flea",             /* 166 */
    "flattery",         /* 167 */
    "flask",            /* 168 */
    "flare",            /* 169 */
    "firefly",          /* 170 */
    "finger",           /* 171 */
    "filtration",       /* 172 */
    "female",           /* 173 */
    "feeder",           /* 174 */
    "feather",          /* 175 */
    "fart",             /* 176 */
    "fang",             /* 177 */
    "failure",          /* 178 */
    "face",             /* 179 */
    "fabrication",      /* 180 */
    "extract",          /* 181 */
    "exodus",           /* 182 */
    "evil",             /* 183 */
    "envy",             /* 184 */
    "enema",            /* 185 */
    "embryo",           /* 186 */
    "egress",           /* 187 */
    "echo",             /* 188 */
    "eater",            /* 189 */
    "ear",              /* 190 */
    "dwarf",            /* 191 */
    "dust",             /* 192 */
    "drop",             /* 193 */
    "draft",            /* 194 */
    "domestication",    /* 195 */
    "distortion",       /* 196 */
    "dew",              /* 197 */
    "depravity",        /* 198 */
    "deity",            /* 199 */
    "death",            /* 200 */
    "daughter",         /* 201 */
    "dash",             /* 202 */
    "dagger",           /* 203 */
    "culture",          /* 204 */
    "crutch",           /* 205 */
    "crow",             /* 206 */
    "critter",          /* 207 */
    "creeper",          /* 208 */
    "creation",         /* 209 */
    "crab",             /* 210 */
    "corruption",       /* 211 */
    "cocoon",           /* 212 */
    "claw",             /* 213 */
    "chip",             /* 214 */
    "child",            /* 215 */
    "cell",             /* 216 */
    "catch",            /* 217 */
    "carving",          /* 218 */
    "carrot",           /* 219 */
    "carnival",         /* 220 */
    "cancer",           /* 221 */
    "butterfly",        /* 222 */
    "burn",             /* 223 */
    "buildup",          /* 224 */
    "brush",            /* 225 */
    "brew",             /* 226 */
    "bottle",           /* 227 */
    "boot",             /* 228 */
    "book",             /* 229 */
    "bone",             /* 230 */
    "blunder",          /* 231 */
    "blot",             /* 232 */
    "blood",            /* 233 */
    "blink",            /* 234 */
    "bite",             /* 235 */
    "bird",             /* 236 */
    "benthos",          /* 237 */
    "beak",             /* 238 */
    "basket",           /* 239 */
    "bark",             /* 240 */
    "ball",             /* 241 */
    "baby",             /* 242 */
    "axolotl",          /* 243 */
    "ashes",            /* 244 */
    "artifact",         /* 245 */
    "arson",            /* 246 */
    "armor",            /* 247 */
    "apparition",       /* 248 */
    "antenna",          /* 249 */
    "alms",             /* 250 */
    "alienation",       /* 251 */
    "advent",           /* 252 */
    "adornment",        /* 253 */
    "abomination",      /* 254 */
    "abandonment",      /* 255 */
};

