
#include "words.h"

const char * const even[256] = {
    "aardvark",     /* 00 */
    "absurd",       /* 01 */
    "accrue",       /* 02 */
    "acme",         /* 03 */
    "adrift",       /* 04 */
    "adult",        /* 05 */
    "afflict",      /* 06 */
    "ahead",        /* 07 */
    "aimless",      /* 08 */
    "Algol",        /* 09 */
    "allow",        /* 0A */
    "alone",        /* 0B */
    "ammo",         /* 0C */
    "ancient",      /* 0D */
    "apple",        /* 0E */
    "artist",       /* 0F */
    "assume",       /* 10 */
    "Athens",       /* 11 */
    "atlas",        /* 12 */
    "Aztec",        /* 13 */
    "baboon",       /* 14 */
    "backfield",    /* 15 */
    "backward",     /* 16 */
    "banjo",        /* 17 */
    "beaming",      /* 18 */
    "bedlamp",      /* 19 */
    "beehive",      /* 1A */
    "beeswax",      /* 1B */
    "befriend",     /* 1C */
    "Belfast",      /* 1D */
    "berserk",      /* 1E */
    "billiard",     /* 1F */
    "bison",        /* 20 */
    "blackjack",    /* 21 */
    "blockade",     /* 22 */
    "blowtorch",    /* 23 */
    "bluebird",     /* 24 */
    "bombast",      /* 25 */
    "bookshelf",    /* 26 */
    "brackish",     /* 27 */
    "breadline",    /* 28 */
    "breakup",      /* 29 */
    "brickyard",    /* 2A */
    "briefcase",    /* 2B */
    "Burbank",      /* 2C */
    "button",       /* 2D */
    "buzzard",      /* 2E */
    "cement",       /* 2F */
    "chairlift",    /* 30 */
    "chatter",      /* 31 */
    "checkup",      /* 32 */
    "chisel",       /* 33 */
    "choking",      /* 34 */
    "chopper",      /* 35 */
    "Christmas",    /* 36 */
    "clamshell",    /* 37 */
    "classic",      /* 38 */
    "classroom",    /* 39 */
    "cleanup",      /* 3A */
    "clockwork",    /* 3B */
    "cobra",        /* 3C */
    "commence",     /* 3D */
    "concert",      /* 3E */
    "cowbell",      /* 3F */
    "crackdown",    /* 40 */
    "cranky",       /* 41 */
    "crowfoot",     /* 42 */
    "crucial",      /* 43 */
    "crumpled",     /* 44 */
    "crusade",      /* 45 */
    "cubic",        /* 46 */
    "dashboard",    /* 47 */
    "deadbolt",     /* 48 */
    "deckhand",     /* 49 */
    "dogsled",      /* 4A */
    "dragnet",      /* 4B */
    "drainage",     /* 4C */
    "dreadful",     /* 4D */
    "drifter",      /* 4E */
    "dropper",      /* 4F */
    "drumbeat",     /* 50 */
    "drunken",      /* 51 */
    "Dupont",       /* 52 */
    "dwelling",     /* 53 */
    "eating",       /* 54 */
    "edict",        /* 55 */
    "egghead",      /* 56 */
    "eightball",    /* 57 */
    "endorse",      /* 58 */
    "endow",        /* 59 */
    "enlist",       /* 5A */
    "erase",        /* 5B */
    "escape",       /* 5C */
    "exceed",       /* 5D */
    "eyeglass",     /* 5E */
    "eyetooth",     /* 5F */
    "facial",       /* 60 */
    "fallout",      /* 61 */
    "flagpole",     /* 62 */
    "flatfoot",     /* 63 */
    "flytrap",      /* 64 */
    "fracture",     /* 65 */
    "framework",    /* 66 */
    "freedom",      /* 67 */
    "frighten",     /* 68 */
    "gazelle",      /* 69 */
    "Geiger",       /* 6A */
    "glitter",      /* 6B */
    "glucose",      /* 6C */
    "goggles",      /* 6D */
    "goldfish",     /* 6E */
    "gremlin",      /* 6F */
    "guidance",     /* 70 */
    "hamlet",       /* 71 */
    "highchair",    /* 72 */
    "hockey",       /* 73 */
    "indoors",      /* 74 */
    "indulge",      /* 75 */
    "inverse",      /* 76 */
    "involve",      /* 77 */
    "island",       /* 78 */
    "jawbone",      /* 79 */
    "keyboard",     /* 7A */
    "kickoff",      /* 7B */
    "kiwi",         /* 7C */
    "klaxon",       /* 7D */
    "locale",       /* 7E */
    "lockup",       /* 7F */
    "merit",        /* 80 */
    "minnow",       /* 81 */
    "miser",        /* 82 */
    "Mohawk",       /* 83 */
    "mural",        /* 84 */
    "music",        /* 85 */
    "necklace",     /* 86 */
    "Neptune",      /* 87 */
    "newborn",      /* 88 */
    "nightbird",    /* 89 */
    "Oakland",      /* 8A */
    "obtuse",       /* 8B */
    "offload",      /* 8C */
    "optic",        /* 8D */
    "orca",         /* 8E */
    "payday",       /* 8F */
    "peachy",       /* 90 */
    "pheasant",     /* 91 */
    "physique",     /* 92 */
    "playhouse",    /* 93 */
    "Pluto",        /* 94 */
    "preclude",     /* 95 */
    "prefer",       /* 96 */
    "preshrunk",    /* 97 */
    "printer",      /* 98 */
    "prowler",      /* 99 */
    "pupil",        /* 9A */
    "puppy",        /* 9B */
    "python",       /* 9C */
    "quadrant",     /* 9D */
    "quiver",       /* 9E */
    "quota",        /* 9F */
    "ragtime",      /* A0 */
    "ratchet",      /* A1 */
    "rebirth",      /* A2 */
    "reform",       /* A3 */
    "regain",       /* A4 */
    "reindeer",     /* A5 */
    "rematch",      /* A6 */
    "repay",        /* A7 */
    "retouch",      /* A8 */
    "revenge",      /* A9 */
    "reward",       /* AA */
    "rhythm",       /* AB */
    "ribcage",      /* AC */
    "ringbolt",     /* AD */
    "robust",       /* AE */
    "rocker",       /* AF */
    "ruffled",      /* B0 */
    "sailboat",     /* B1 */
    "sawdust",      /* B2 */
    "scallion",     /* B3 */
    "scenic",       /* B4 */
    "scorecard",    /* B5 */
    "Scotland",     /* B6 */
    "seabird",      /* B7 */
    "select",       /* B8 */
    "sentence",     /* B9 */
    "shadow",       /* BA */
    "shamrock",     /* BB */
    "showgirl",     /* BC */
    "skullcap",     /* BD */
    "skydive",      /* BE */
    "slingshot",    /* BF */
    "slowdown",     /* C0 */
    "snapline",     /* C1 */
    "snapshot",     /* C2 */
    "snowcap",      /* C3 */
    "snowslide",    /* C4 */
    "solo",         /* C5 */
    "southward",    /* C6 */
    "soybean",      /* C7 */
    "spaniel",      /* C8 */
    "spearhead",    /* C9 */
    "spellbind",    /* CA */
    "spheroid",     /* CB */
    "spigot",       /* CC */
    "spindle",      /* CD */
    "spyglass",     /* CE */
    "stagehand",    /* CF */
    "stagnate",     /* D0 */
    "stairway",     /* D1 */
    "standard",     /* D2 */
    "stapler",      /* D3 */
    "steamship",    /* D4 */
    "sterling",     /* D5 */
    "stockman",     /* D6 */
    "stopwatch",    /* D7 */
    "stormy",       /* D8 */
    "sugar",        /* D9 */
    "surmount",     /* DA */
    "suspense",     /* DB */
    "sweatband",    /* DC */
    "swelter",      /* DD */
    "tactics",      /* DE */
    "talon",        /* DF */
    "tapeworm",     /* E0 */
    "tempest",      /* E1 */
    "tiger",        /* E2 */
    "tissue",       /* E3 */
    "tonic",        /* E4 */
    "topmost",      /* E5 */
    "tracker",      /* E6 */
    "transit",      /* E7 */
    "trauma",       /* E8 */
    "treadmill",    /* E9 */
    "Trojan",       /* EA */
    "trouble",      /* EB */
    "tumor",        /* EC */
    "tunnel",       /* ED */
    "tycoon",       /* EE */
    "uncut",        /* EF */
    "unearth",      /* F0 */
    "unwind",       /* F1 */
    "uproot",       /* F2 */
    "upset",        /* F3 */
    "upshot",       /* F4 */
    "vapor",        /* F5 */
    "village",      /* F6 */
    "virus",        /* F7 */
    "Vulcan",       /* F8 */
    "waffle",       /* F9 */
    "wallet",       /* FA */
    "watchword",    /* FB */
    "wayside",      /* FC */
    "willow",       /* FD */
    "woodlark",     /* FE */
    "Zulu"          /* FF */
};

const char * const odd[256] = {
    "aardvark",     /* 00 */
    "absurd",       /* 01 */
    "accrue",       /* 02 */
    "acme",         /* 03 */
    "adrift",       /* 04 */
    "adult",        /* 05 */
    "afflict",      /* 06 */
    "ahead",        /* 07 */
    "aimless",      /* 08 */
    "Algol",        /* 09 */
    "allow",        /* 0A */
    "alone",        /* 0B */
    "ammo",         /* 0C */
    "ancient",      /* 0D */
    "apple",        /* 0E */
    "artist",       /* 0F */
    "assume",       /* 10 */
    "Athens",       /* 11 */
    "atlas",        /* 12 */
    "Aztec",        /* 13 */
    "baboon",       /* 14 */
    "backfield",    /* 15 */
    "backward",     /* 16 */
    "banjo",        /* 17 */
    "beaming",      /* 18 */
    "bedlamp",      /* 19 */
    "beehive",      /* 1A */
    "beeswax",      /* 1B */
    "befriend",     /* 1C */
    "Belfast",      /* 1D */
    "berserk",      /* 1E */
    "billiard",     /* 1F */
    "bison",        /* 20 */
    "blackjack",    /* 21 */
    "blockade",     /* 22 */
    "blowtorch",    /* 23 */
    "bluebird",     /* 24 */
    "bombast",      /* 25 */
    "bookshelf",    /* 26 */
    "brackish",     /* 27 */
    "breadline",    /* 28 */
    "breakup",      /* 29 */
    "brickyard",    /* 2A */
    "briefcase",    /* 2B */
    "Burbank",      /* 2C */
    "button",       /* 2D */
    "buzzard",      /* 2E */
    "cement",       /* 2F */
    "chairlift",    /* 30 */
    "chatter",      /* 31 */
    "checkup",      /* 32 */
    "chisel",       /* 33 */
    "choking",      /* 34 */
    "chopper",      /* 35 */
    "Christmas",    /* 36 */
    "clamshell",    /* 37 */
    "classic",      /* 38 */
    "classroom",    /* 39 */
    "cleanup",      /* 3A */
    "clockwork",    /* 3B */
    "cobra",        /* 3C */
    "commence",     /* 3D */
    "concert",      /* 3E */
    "cowbell",      /* 3F */
    "crackdown",    /* 40 */
    "cranky",       /* 41 */
    "crowfoot",     /* 42 */
    "crucial",      /* 43 */
    "crumpled",     /* 44 */
    "crusade",      /* 45 */
    "cubic",        /* 46 */
    "dashboard",    /* 47 */
    "deadbolt",     /* 48 */
    "deckhand",     /* 49 */
    "dogsled",      /* 4A */
    "dragnet",      /* 4B */
    "drainage",     /* 4C */
    "dreadful",     /* 4D */
    "drifter",      /* 4E */
    "dropper",      /* 4F */
    "drumbeat",     /* 50 */
    "drunken",      /* 51 */
    "Dupont",       /* 52 */
    "dwelling",     /* 53 */
    "eating",       /* 54 */
    "edict",        /* 55 */
    "egghead",      /* 56 */
    "eightball",    /* 57 */
    "endorse",      /* 58 */
    "endow",        /* 59 */
    "enlist",       /* 5A */
    "erase",        /* 5B */
    "escape",       /* 5C */
    "exceed",       /* 5D */
    "eyeglass",     /* 5E */
    "eyetooth",     /* 5F */
    "facial",       /* 60 */
    "fallout",      /* 61 */
    "flagpole",     /* 62 */
    "flatfoot",     /* 63 */
    "flytrap",      /* 64 */
    "fracture",     /* 65 */
    "framework",    /* 66 */
    "freedom",      /* 67 */
    "frighten",     /* 68 */
    "gazelle",      /* 69 */
    "Geiger",       /* 6A */
    "glitter",      /* 6B */
    "glucose",      /* 6C */
    "goggles",      /* 6D */
    "goldfish",     /* 6E */
    "gremlin",      /* 6F */
    "guidance",     /* 70 */
    "hamlet",       /* 71 */
    "highchair",    /* 72 */
    "hockey",       /* 73 */
    "indoors",      /* 74 */
    "indulge",      /* 75 */
    "inverse",      /* 76 */
    "involve",      /* 77 */
    "island",       /* 78 */
    "jawbone",      /* 79 */
    "keyboard",     /* 7A */
    "kickoff",      /* 7B */
    "kiwi",         /* 7C */
    "klaxon",       /* 7D */
    "locale",       /* 7E */
    "lockup",       /* 7F */
    "merit",        /* 80 */
    "minnow",       /* 81 */
    "miser",        /* 82 */
    "Mohawk",       /* 83 */
    "mural",        /* 84 */
    "music",        /* 85 */
    "necklace",     /* 86 */
    "Neptune",      /* 87 */
    "newborn",      /* 88 */
    "nightbird",    /* 89 */
    "Oakland",      /* 8A */
    "obtuse",       /* 8B */
    "offload",      /* 8C */
    "optic",        /* 8D */
    "orca",         /* 8E */
    "payday",       /* 8F */
    "peachy",       /* 90 */
    "pheasant",     /* 91 */
    "physique",     /* 92 */
    "playhouse",    /* 93 */
    "Pluto",        /* 94 */
    "preclude",     /* 95 */
    "prefer",       /* 96 */
    "preshrunk",    /* 97 */
    "printer",      /* 98 */
    "prowler",      /* 99 */
    "pupil",        /* 9A */
    "puppy",        /* 9B */
    "python",       /* 9C */
    "quadrant",     /* 9D */
    "quiver",       /* 9E */
    "quota",        /* 9F */
    "ragtime",      /* A0 */
    "ratchet",      /* A1 */
    "rebirth",      /* A2 */
    "reform",       /* A3 */
    "regain",       /* A4 */
    "reindeer",     /* A5 */
    "rematch",      /* A6 */
    "repay",        /* A7 */
    "retouch",      /* A8 */
    "revenge",      /* A9 */
    "reward",       /* AA */
    "rhythm",       /* AB */
    "ribcage",      /* AC */
    "ringbolt",     /* AD */
    "robust",       /* AE */
    "rocker",       /* AF */
    "ruffled",      /* B0 */
    "sailboat",     /* B1 */
    "sawdust",      /* B2 */
    "scallion",     /* B3 */
    "scenic",       /* B4 */
    "scorecard",    /* B5 */
    "Scotland",     /* B6 */
    "seabird",      /* B7 */
    "select",       /* B8 */
    "sentence",     /* B9 */
    "shadow",       /* BA */
    "shamrock",     /* BB */
    "showgirl",     /* BC */
    "skullcap",     /* BD */
    "skydive",      /* BE */
    "slingshot",    /* BF */
    "slowdown",     /* C0 */
    "snapline",     /* C1 */
    "snapshot",     /* C2 */
    "snowcap",      /* C3 */
    "snowslide",    /* C4 */
    "solo",         /* C5 */
    "southward",    /* C6 */
    "soybean",      /* C7 */
    "spaniel",      /* C8 */
    "spearhead",    /* C9 */
    "spellbind",    /* CA */
    "spheroid",     /* CB */
    "spigot",       /* CC */
    "spindle",      /* CD */
    "spyglass",     /* CE */
    "stagehand",    /* CF */
    "stagnate",     /* D0 */
    "stairway",     /* D1 */
    "standard",     /* D2 */
    "stapler",      /* D3 */
    "steamship",    /* D4 */
    "sterling",     /* D5 */
    "stockman",     /* D6 */
    "stopwatch",    /* D7 */
    "stormy",       /* D8 */
    "sugar",        /* D9 */
    "surmount",     /* DA */
    "suspense",     /* DB */
    "sweatband",    /* DC */
    "swelter",      /* DD */
    "tactics",      /* DE */
    "talon",        /* DF */
    "tapeworm",     /* E0 */
    "tempest",      /* E1 */
    "tiger",        /* E2 */
    "tissue",       /* E3 */
    "tonic",        /* E4 */
    "topmost",      /* E5 */
    "tracker",      /* E6 */
    "transit",      /* E7 */
    "trauma",       /* E8 */
    "treadmill",    /* E9 */
    "Trojan",       /* EA */
    "trouble",      /* EB */
    "tumor",        /* EC */
    "tunnel",       /* ED */
    "tycoon",       /* EE */
    "uncut",        /* EF */
    "unearth",      /* F0 */
    "unwind",       /* F1 */
    "uproot",       /* F2 */
    "upset",        /* F3 */
    "upshot",       /* F4 */
    "vapor",        /* F5 */
    "village",      /* F6 */
    "virus",        /* F7 */
    "Vulcan",       /* F8 */
    "waffle",       /* F9 */
    "wallet",       /* FA */
    "watchword",    /* FB */
    "wayside",      /* FC */
    "willow",       /* FD */
    "woodlark",     /* FE */
    "Zulu",         /* FF */
};

